[package]
name = "tty-ui"
description = "Flexible UI builder for TTY-based interfaces."
authors = ["Daniel Way <contact@danieldway.com>"]
license = "MIT"
repository = "https://github.com/danielway/cibushub"
version = "0.1.0"
edition = "2021"
exclude = [".github"]

[dependencies]
